from __future__ import annotations

import re
import uuid
from typing import Any

from config import config


# ----------------------------------------------------------------------
# Unique codes
# ----------------------------------------------------------------------

_CODE_RE = re.compile(r"^[0-9a-fA-F]{32}$")


def generate_code() -> str:
    """Return a 32-char hex UUID4 used as the public retrieval code."""
    return uuid.uuid4().hex


def is_valid_code(code: str) -> bool:
    """True if `code` matches the format generated by `generate_code`."""
    return bool(code) and bool(_CODE_RE.match(code.strip()))


# ----------------------------------------------------------------------
# Human-readable formatting
# ----------------------------------------------------------------------

def humanize_bytes(num: int) -> str:
    """Convert a byte count to a short human string, e.g. '12.3 MB'."""
    n = float(num)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if abs(n) < 1024.0:
            return f"{n:.1f} {unit}" if unit != "B" else f"{int(n)} {unit}"
        n /= 1024.0
    return f"{n:.1f} PB"


# ----------------------------------------------------------------------
# Subscription enforcement
# ----------------------------------------------------------------------

def tier_limits(tier: str) -> tuple[int, int]:
    """
    Return (single_file_limit_bytes, total_quota_bytes) for the given tier.
    Defaults to free if tier is unknown.
    """
    sub = config.subscription
    if tier == "premium":
        return sub.premium_single_file_bytes, sub.premium_total_quota_bytes
    return sub.free_single_file_bytes, sub.free_total_quota_bytes


def check_upload_allowed(user: dict[str, Any], incoming_size: int) -> tuple[bool, str]:
    """
    Decide whether a user is allowed to upload `incoming_size` bytes.

    Returns (ok, reason_if_not_ok).
    """
    tier = user.get("subscription", "free")
    used = int(user.get("used_bytes", 0))
    single_limit, total_limit = tier_limits(tier)

    if incoming_size <= 0:
        return False, "حجم فایل نامعتبر است."

    if incoming_size > single_limit:
        return False, (
            f"حجم این فایل ({humanize_bytes(incoming_size)}) از سقف مجاز "
            f"اشتراک {tier} ({humanize_bytes(single_limit)} برای هر فایل) بیشتر است."
        )

    if used + incoming_size > total_limit:
        remaining = max(total_limit - used, 0)
        return False, (
            f"حجم باقی‌مانده اشتراک شما کافی نیست. "
            f"باقی‌مانده: {humanize_bytes(remaining)} — "
            f"حجم این فایل: {humanize_bytes(incoming_size)}."
        )

    return True, ""


def remaining_quota(user: dict[str, Any]) -> int:
    """Return remaining bytes in the user's total quota (>=0)."""
    _, total_limit = tier_limits(user.get("subscription", "free"))
    used = int(user.get("used_bytes", 0))
    return max(total_limit - used, 0)
